### ISSUE TITLE
rsync operation not supported (95)

### ISSUE THREAD

**Issue by brianwfreeman** [lmacken/plow#5]
I am getting this error/warning: "rsync: [receiver] do_fallocate "/media/brian/1/plot-k32-2023-02-23-15-35-53813e969347bbe40466e51b7048dc18512700bbee55a38d1ef43a1ee58b205e.plot": Operation not supported (95)"

The destination disk is formatted in NTFS.  The source disk is formatted in XFS.  How do I get rid of this error?

**Comment by sten0814** [comment]
same issue here, my system runs at arch linux, i use ext4 (source) and exfat (destination)

thank anybody for help

**Comment by lmacken** [comment]
Try removing the `--preallocate` flag from the `RSYNC_FLAGS`

**Comment by nonfungiblejson** [comment]
Had the same issue with an NTFS that I was using just to test plot move times. Removing `--preallocate` worked for me.
